printWidth: 120
tabWidth: 4
useTabs: false
endOfLine: lf
trailingComma: all
semi: false
singleQuote: true
importOrderSortSpecifiers: true
importOrderSeparation: true

plugins:
    - '@trivago/prettier-plugin-sort-imports'

overrides:
    - files:
          - '*.ts'
          - 'eslint.config.mjs'
      options:
          # trivago/prettier-plugin-sort-imports (using regex)
          importOrder:
              - .+
    # expect all *.json files to be jsonc
    - files: '*.json'
      options:
          parser: jsonc
    # except for package.json
    - files: 'package.json'
      options:
          parser: json
    - files: '*.yaml'
      options:
          parser: yaml
